# Generated by Django 5.0.3 on 2024-05-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
        ('store', '0005_product_category'),
    ]

    operations = [
    ]
