# Generated by Django 5.0.3 on 2024-05-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_amount_paid_alter_orderitem_price'),
        ('payment', '0009_order_orderitem'),
    ]

    operations = [
    ]
